# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Black check
        run: python -m black --check .
      - name: Ruff check
        run: python -m ruff check .

      - name: Restore mypy cache
        id: cache-mypy-restore
        uses: actions/cache/restore@v3
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-mypy
      - name: Mypy check
        run: python -m mypy .
      - name: Save mypy cache
        id: cache-mypy-save
        uses: actions/cache/save@v3
        with:
          path: .mypy_cache
          key: ${{ steps.cache-mypy-restore.outputs.cache-primary-key }}

      - name: Pytest
        run: python -m pytest .
